### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [yetanalytics/re-mdl#23]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by kelvinqian00** [comment]
Hello @codehangen,

Apologies for not seeing this issue (the original issue opening got buried, and we just saw the issue closing notification). But as you might have guessed, this library is indeed no longer maintained.

**Comment by ghost** [comment]
Hi kelvinqian00.

> Hello @codehangen,
> Apologies for not seeing this issue (the original issue opening got buried, and we just saw the issue closing notification). But as you might have guessed, this library is indeed no longer maintained.

thank you for feedback.
