### ISSUE TITLE
Library shows up as wrong language (css instead of clojure)

### ISSUE THREAD

**Issue by gadfly361** [yetanalytics/re-mdl#3]
Library shows up as `css` instead of `clojure`.

![image](https://cloud.githubusercontent.com/assets/8610039/11967365/1828a802-a8b7-11e5-8b46-14f72f7a938a.png)

I think this is happening because of these [css files](https://github.com/yetanalytics/re-mdl/tree/master/resources/public/css).  Should be fixed if you place the `css` folder inside a folder called `vendor`.

resource/public/css --> resources/public/vendor/css

**Comment by milt** [comment]
Ain't that the damndest thing.
